### ISSUE TITLE
Program error when starting

### ISSUE THREAD

**Issue by kthamlin** [DanCech/myq-bridge#2]
I'm wanting to use this to control a LiftMaster 821LM MyQ wifi garage door control.  The program starts and then errors out:

pi@raspberrypi:~/myq$ ./myq.py
2016-05-03 22:33:59,162 Starting
2016-05-03 22:33:59,175 Getting Doors
Traceback (most recent call last):
  File "./myq.py", line 509, in <module>
    sys.exit(main())
  File "./myq.py", line 496, in main
    myq.get_doors()
  File "./myq.py", line 124, in get_doors
    state = Door.STATES[int(attr['Value'])]
IndexError: list index out of range

I ran the program with debug turned on and it seems to be returning the correct attribute information from the initial query. 

Thanks in advance for any help you can give me.

**Comment by DanCech** [comment]
That indicates that the MyQ web service is returning a value the script doesn't recognize.  I just pushed an update to make it log the received value instead of failing, can you give that a try and see what information you get?  You should see a log line like "ERROR Invalid door state "2" for door Main Door"

**Comment by kthamlin** [comment]
That seems to have fixed the problem.  Here is the output now:

pi@raspberrypi:~/myq $ ./myq.py
2016-05-04 08:34:47,773 INFO Starting
2016-05-04 08:34:47,785 INFO Getting Doors
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
- Restarting with stat
  2016-05-04 08:34:49,305 INFO Starting
  2016-05-04 08:34:49,318 INFO Getting Doors
- Debugger is active!
- Debugger pin code: 178-680-202

I am able to open & close the garage door through the http commands in the browser now.

**Comment by DanCech** [comment]
Glad to hear it's working! That indicates the door status is something we understand now, where before it wasn't.

If you do see any error messages about "Invalid door state" please let me know.

**Comment by kthamlin** [comment]
OK Dan, thanks for your help!
